plugins {
    id 'maven-publish'
}

group = 'com.github.Impopite'
version = '1.0'

tasks.register('sourceJar', Jar) {
    from sourceSets.main.allJava
    archiveClassifier = "sources"
}

tasks.register('javadocJar', Jar) {
    from javadoc
    archiveClassifier = "javadoc"
}

publishing {
    publications {
        library(MavenPublication) {
            from components.java
            artifact sourceJar
            artifact javadocJar
        }
    }
}

